sudo: false

language:
  - python

python:
  - 3.6.8

install:
  - pip install -r requirements.txt

script:
  - black RPx/detector/src.py
  - black RPx/utils/src.py
  - pytest --cov=RPx
  - pip install .

notifications:
  email: false

after_success:
  - coveralls
