sudo: false

language:
  - python

python:
  - 3.6.8

install:
  - pip install -r requirements.txt

script:
  - travis_wait 35 pytest --cov=RPx
  - pip install .

notifications:
  email: false

after_success:
  - coveralls
