sudo: false

language:
  - python

python:
  - 2.7
  - 3.6.8

install:
  - pip install -r requirements.txt

script:
  - pycodestyle RPx
  - pytest --verbose --capture=no RPx
  - pip install .

notifications:
  email: false